spring.application.name=enquetes-api

# Configuration de la base de données (Sécurisée par variables d'environnement)
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:smf_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuration JWT (Clé secrète sécurisée)
application.security.jwt.secret-key=${JWT_SECRET:une_cle_secrete_par_defaut_tres_longue_pour_le_dev_local_uniquement_12345!}
application.security.jwt.expiration=36000000

server.address=0.0.0.0