spring.application.name=enquetes-api
spring.datasource.url=jdbc:postgresql://localhost:5432/smf_db
spring.datasource.username=Ezechiel
spring.datasource.password=brouezechiel2102
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuration JWT
# Collez ici la clé que vous avez générée à l'étape 1
application.security.jwt.secret-key=${JWT_SECRET:une_cle_secrete_par_defaut_tres_longue_pour_le_dev_local_uniquement_12345!}
application.security.jwt.expiration=36000000
server.address=0.0.0.0